@startuml
class edu.utfpr.cp.dacom.sa.soilcorrection.Nutrientes.NutrientesCTC
enum edu.utfpr.cp.dacom.sa.soilcorrection.Textura.TexturaSolo
edu.utfpr.cp.dacom.sa.soilcorrection.Textura.TexturaSolo ..> edu.utfpr.cp.dacom.sa.soilcorrection.Nutrientes.NutrientesCTC
@enduml